import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ListChecks, Search, RefreshCw, Users, PenLine, FolderCheck, Trophy, Loader2, CheckCircle2, XCircle, Clock3 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AdminPageHeader, AdminMetric, CategoryPill, adminPanelClass } from "@/components/admin/AdminWorkspace";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/admin/seleksi")({ component: AdminSeleksi });
type Kind="prestasi"|"ekonomi"|"umum"; type Status="pending"|"approved"|"rejected";
type Registration={id:string;full_name:string;email:string;school_name:string;education_level:string;kind:Kind;token:string|null;candidate_status:Status|null;created_at:string};
type StageRow=Registration&{hasEssay:boolean;documentCount:number};

function AdminSeleksi(){
  const [rows,setRows]=useState<StageRow[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [stage,setStage]=useState("all"); const [kind,setKind]=useState<"all"|Kind>("all");
  const load=async()=>{setLoading(true);const [r,d,e]=await Promise.all([supabase.from("registrations").select("id,full_name,email,school_name,education_level,kind,token,candidate_status,created_at").order("created_at",{ascending:false}),supabase.from("documents").select("registration_id,email,kind"),supabase.from("site_settings").select("key").like("key","study_case_%")]);if(r.error)toast.error("Tahapan seleksi gagal dimuat");const docs=d.data??[];const essayKeys=new Set((e.data??[]).map(x=>x.key.toLowerCase()));setRows(((r.data??[]) as Registration[]).map(x=>({...x,hasEssay:!!x.token&&essayKeys.has(`study_case_${x.token.toLowerCase()}`),documentCount:docs.filter(doc=>doc.registration_id===x.id||(doc.email.toLowerCase()===x.email.toLowerCase()&&doc.kind===x.kind)).length})));setLoading(false)};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>rows.filter(r=>{if(kind!=="all"&&r.kind!==kind)return false;if(stage==="essay"&&!r.hasEssay)return false;if(stage==="documents"&&!r.documentCount)return false;if(stage==="review"&&(!r.hasEssay||!r.documentCount||r.candidate_status==="approved"))return false;if(stage==="approved"&&r.candidate_status!=="approved")return false;if(stage==="rejected"&&r.candidate_status!=="rejected")return false;const s=query.toLowerCase();return !s||[r.full_name,r.email,r.school_name,r.token].some(v=>v?.toLowerCase().includes(s))}),[rows,kind,stage,query]);
  const updateStatus=async(row:StageRow,status:Status)=>{const {error}=await supabase.from("registrations").update({candidate_status:status,candidate_reviewed_at:new Date().toISOString()}).eq("id",row.id);if(error)return toast.error(error.message);setRows(prev=>prev.map(x=>x.id===row.id?{...x,candidate_status:status}:x));toast.success(status==="approved"?"Peserta ditetapkan sebagai kandidat lolos":status==="rejected"?"Peserta tidak diloloskan":"Status dikembalikan ke review")};
  const approved=rows.filter(r=>r.candidate_status==="approved").length, essays=rows.filter(r=>r.hasEssay).length, documented=rows.filter(r=>r.documentCount>0).length;
  return <div className="space-y-5"><AdminPageHeader eyebrow="Tahap 04 · Review" title="Tahapan Seleksi" description="Pantau perjalanan setiap peserta dari pendaftaran, studi kasus, administrasi program, hingga keputusan akhir." icon={ListChecks} actions={<Button variant="outline" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>Muat ulang</Button>}/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><AdminMetric label="Pendaftar" value={rows.length} helper="Tahap awal" icon={Users}/><AdminMetric label="Studi kasus" value={essays} helper={`${rows.length?Math.round(essays/rows.length*100):0}% dari pendaftar`} icon={PenLine} tone="sky"/><AdminMetric label="Berkas masuk" value={documented} helper="Siap ditinjau" icon={FolderCheck} tone="amber"/><AdminMetric label="Kandidat lolos" value={approved} helper="Keputusan final" icon={Trophy} tone="emerald"/></div>
    <section className={cn(adminPanelClass,"overflow-hidden")}><div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-[1fr_auto_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari peserta atau kode registrasi" className="h-11 rounded-xl pl-9"/></div><select value={stage} onChange={e=>setStage(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">Semua tahapan</option><option value="essay">Sudah isi studi kasus</option><option value="documents">Sudah kirim berkas</option><option value="review">Siap direview</option><option value="approved">Kandidat lolos</option><option value="rejected">Tidak lolos</option></select><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">Semua kategori</option><option value="prestasi">Prestasi</option><option value="ekonomi">Ekonomi</option><option value="umum">Umum</option></select></div>
      {loading?<div className="grid min-h-52 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-violet-600"/></div>:filtered.length===0?<div className="py-16 text-center text-sm text-slate-500">Tidak ada peserta pada filter ini.</div>:<div className="divide-y divide-slate-100">{filtered.map(r=><article key={r.id} className="grid gap-4 p-4 transition hover:bg-slate-50/60 lg:grid-cols-[minmax(220px,1.2fr)_minmax(280px,1.5fr)_auto] lg:items-center lg:p-5"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black text-slate-950">{r.full_name}</p><CategoryPill kind={r.kind}/></div><p className="mt-1 font-mono text-xs text-slate-500">{r.token??"Tanpa kode"}</p><p className="mt-1 text-xs text-slate-400">{r.school_name}</p></div><div className="grid grid-cols-3 gap-2">{([{label:"Daftar",done:true,Icon:Users},{label:"Studi kasus",done:!!r.hasEssay,Icon:PenLine},{label:"Berkas",done:r.documentCount>0,Icon:FolderCheck}]).map(({label,done,Icon})=><div key={String(label)} className={cn("rounded-xl border p-2.5",done?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-slate-50")}><Icon className={cn("h-4 w-4",done?"text-emerald-600":"text-slate-400")}/><p className="mt-1.5 text-[10px] font-bold text-slate-600">{label}</p></div>)}</div><div className="flex flex-wrap gap-2 lg:justify-end">{r.candidate_status==="approved"?<span className="inline-flex items-center rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 className="mr-1.5 h-4 w-4"/>Lolos</span>:r.candidate_status==="rejected"?<span className="inline-flex items-center rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700"><XCircle className="mr-1.5 h-4 w-4"/>Tidak lolos</span>:<span className="inline-flex items-center rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Clock3 className="mr-1.5 h-4 w-4"/>Review</span>}<Button size="sm" disabled={!r.hasEssay||!r.documentCount} onClick={()=>updateStatus(r,"approved")}>Loloskan</Button><Button size="sm" variant="outline" onClick={()=>updateStatus(r,"rejected")}>Tolak</Button></div></article>)}</div>}
    </section></div>
}
